/**
 * The difficulty ladder — generated by tools/build-ladder.ts, not written by hand.
 *
 * Rebuild with `pnpm ladder`. Do not edit: these boards are in players'
 * histories by level id, so changing one silently swaps the puzzle under
 * somebody's solved result.
 */

import type { Puzzle } from './engine';

/** Everything except the fields that identify a puzzle rather than describe it. */
export type Board = Omit<Puzzle, 'id' | 'game' | 'date' | 'number' | 'difficulty'>;

export interface Rung {
  chapter: string;
  title: string;
  teaches: string;
  difficulty: 1 | 2 | 3;
  /** kept behind its own key so it can be spread into a Puzzle without
      dragging the chapter's own fields in with it */
  board: Board;
}

export const LADDER: Rung[] = [
  {
    chapter: 'ladder-01',
    title: "On your own",
    teaches: "No new rules from here. Just boards.",
    difficulty: 1,
    board: {
      w: 7,
      h: 6,
      islands: [{"x":4,"y":3,"n":5},{"x":6,"y":3,"n":3},{"x":6,"y":1,"n":3},{"x":0,"y":3,"n":3},{"x":4,"y":0,"n":5},{"x":6,"y":0,"n":4},{"x":2,"y":0,"n":4},{"x":0,"y":0,"n":2},{"x":2,"y":2,"n":2},{"x":6,"y":5,"n":1}],
    },
  },
  {
    chapter: 'ladder-02',
    title: "A little more",
    teaches: "Same size, less given away.",
    difficulty: 1,
    board: {
      w: 7,
      h: 7,
      islands: [{"x":3,"y":3,"n":6},{"x":3,"y":0,"n":3},{"x":6,"y":3,"n":3},{"x":5,"y":3,"n":4},{"x":5,"y":0,"n":3},{"x":0,"y":3,"n":1},{"x":6,"y":6,"n":2},{"x":3,"y":6,"n":4},{"x":1,"y":6,"n":2},{"x":3,"y":2,"n":2}],
    },
  },
  {
    chapter: 'ladder-03',
    title: "Middling",
    teaches: "Bigger. Everything still follows.",
    difficulty: 2,
    board: {
      w: 9,
      h: 7,
      islands: [{"x":2,"y":6,"n":4},{"x":0,"y":6,"n":3},{"x":4,"y":6,"n":4},{"x":2,"y":2,"n":5},{"x":7,"y":6,"n":1},{"x":6,"y":2,"n":6},{"x":0,"y":2,"n":3},{"x":4,"y":3,"n":5},{"x":0,"y":3,"n":3},{"x":2,"y":5,"n":2},{"x":6,"y":0,"n":2},{"x":4,"y":0,"n":1},{"x":6,"y":3,"n":4},{"x":8,"y":2,"n":3},{"x":2,"y":3,"n":3},{"x":8,"y":5,"n":1}],
    },
  },
  {
    chapter: 'ladder-04',
    title: "Keep going",
    teaches: "You will need to look further ahead.",
    difficulty: 2,
    board: {
      w: 8,
      h: 9,
      islands: [{"x":4,"y":6,"n":4},{"x":4,"y":4,"n":7},{"x":0,"y":6,"n":2},{"x":0,"y":4,"n":3},{"x":1,"y":4,"n":5},{"x":1,"y":1,"n":4},{"x":4,"y":0,"n":4},{"x":4,"y":1,"n":4},{"x":2,"y":6,"n":3},{"x":0,"y":2,"n":2},{"x":0,"y":0,"n":3},{"x":3,"y":1,"n":2},{"x":3,"y":0,"n":4},{"x":7,"y":4,"n":1},{"x":4,"y":8,"n":1},{"x":2,"y":8,"n":1}],
    },
  },
  {
    chapter: 'ladder-05',
    title: "Most of a week",
    teaches: "About as hard as a Wednesday.",
    difficulty: 2,
    board: {
      w: 9,
      h: 7,
      islands: [{"x":2,"y":4,"n":4},{"x":2,"y":6,"n":5},{"x":5,"y":6,"n":6},{"x":5,"y":2,"n":3},{"x":0,"y":6,"n":3},{"x":4,"y":4,"n":3},{"x":8,"y":2,"n":3},{"x":2,"y":0,"n":2},{"x":2,"y":2,"n":2},{"x":5,"y":4,"n":6},{"x":7,"y":4,"n":3},{"x":0,"y":3,"n":3},{"x":4,"y":0,"n":1},{"x":8,"y":4,"n":2},{"x":0,"y":1,"n":2},{"x":7,"y":6,"n":2}],
    },
  },
  {
    chapter: 'ladder-06',
    title: "Sunday sized",
    teaches: "This is what the weekend looks like.",
    difficulty: 3,
    board: {
      w: 11,
      h: 11,
      islands: [{"x":10,"y":8,"n":2},{"x":10,"y":4,"n":6},{"x":8,"y":4,"n":6},{"x":8,"y":0,"n":3},{"x":8,"y":6,"n":4},{"x":10,"y":7,"n":2},{"x":8,"y":1,"n":5},{"x":4,"y":6,"n":6},{"x":4,"y":10,"n":6},{"x":2,"y":6,"n":3},{"x":7,"y":10,"n":4},{"x":7,"y":8,"n":4},{"x":0,"y":6,"n":3},{"x":10,"y":6,"n":3},{"x":1,"y":10,"n":3},{"x":10,"y":1,"n":3},{"x":5,"y":0,"n":1},{"x":5,"y":8,"n":1},{"x":0,"y":3,"n":2},{"x":1,"y":8,"n":1}],
    },
  },
  {
    chapter: 'ladder-07',
    title: "The last one",
    teaches: "Finish this and the daily is yours.",
    difficulty: 3,
    board: {
      w: 11,
      h: 13,
      islands: [{"x":3,"y":10,"n":5},{"x":3,"y":7,"n":3},{"x":5,"y":10,"n":4},{"x":5,"y":8,"n":4},{"x":7,"y":8,"n":3},{"x":0,"y":7,"n":2},{"x":7,"y":10,"n":5},{"x":1,"y":10,"n":5},{"x":7,"y":12,"n":2},{"x":3,"y":8,"n":2},{"x":0,"y":9,"n":3},{"x":7,"y":4,"n":4},{"x":10,"y":10,"n":4},{"x":4,"y":4,"n":1},{"x":3,"y":9,"n":4},{"x":10,"y":6,"n":2},{"x":3,"y":12,"n":4},{"x":1,"y":12,"n":4},{"x":7,"y":0,"n":2},{"x":1,"y":9,"n":5}],
    },
  },
];
