/**
 * The difficulty ladder — generated by tools/build-ladder.ts, not written by hand.
 *
 * Rebuild with `pnpm ladder`. Do not edit: these boards are in players'
 * histories by level id, so changing one silently swaps the puzzle under
 * somebody's solved result.
 */

import type { Puzzle } from './engine';

/** Everything except the fields that identify a puzzle rather than describe it. */
export type Board = Omit<Puzzle, 'id' | 'game' | 'date' | 'number' | 'difficulty'>;

export interface Rung {
  chapter: string;
  title: string;
  teaches: string;
  difficulty: 1 | 2 | 3;
  /** kept behind its own key so it can be spread into a Puzzle without
      dragging the chapter's own fields in with it */
  board: Board;
}

export const LADDER: Rung[] = [
  {
    chapter: 'ladder-01',
    title: "On your own",
    teaches: "No new rules from here. Just boards.",
    difficulty: 1,
    board: {
      n: 8,
      stars: 2,
      regions: [1,1,1,3,3,7,7,2,1,1,3,3,3,7,7,2,1,1,1,3,3,3,7,2,5,5,5,5,6,6,7,2,5,5,5,4,6,6,7,7,5,4,4,4,4,6,6,7,7,4,4,7,7,7,7,7,7,7,7,7,0,0,0,0],
    },
  },
  {
    chapter: 'ladder-02',
    title: "A little more",
    teaches: "Same size, less given away.",
    difficulty: 1,
    board: {
      n: 8,
      stars: 2,
      regions: [5,7,7,7,1,1,7,7,5,7,3,7,1,7,7,2,5,7,3,7,1,7,2,2,5,7,3,7,7,7,2,2,5,7,7,6,6,6,6,2,0,0,7,6,6,6,4,2,0,0,7,7,6,4,4,4,0,0,0,7,4,4,4,4],
    },
  },
  {
    chapter: 'ladder-03',
    title: "Middling",
    teaches: "Bigger. Everything still follows.",
    difficulty: 2,
    board: {
      n: 9,
      stars: 2,
      regions: [2,2,2,1,1,1,8,8,3,2,2,1,1,8,8,8,3,3,2,2,1,1,8,5,5,5,3,6,2,1,1,8,5,3,3,3,6,2,4,4,8,5,5,3,3,6,2,4,4,7,5,5,7,7,6,6,4,7,7,7,7,7,7,6,6,4,4,7,0,0,0,7,6,4,4,4,4,0,0,0,7],
    },
  },
  {
    chapter: 'ladder-04',
    title: "Keep going",
    teaches: "You will need to look further ahead.",
    difficulty: 2,
    board: {
      n: 9,
      stars: 2,
      regions: [7,7,7,7,7,8,8,8,8,7,7,3,3,7,4,4,8,8,3,3,3,4,4,4,8,8,1,5,3,3,3,4,4,1,1,1,5,3,5,4,4,4,1,1,1,5,3,5,2,2,2,2,2,1,5,5,5,2,2,0,2,2,2,5,6,6,6,0,0,0,0,2,6,6,6,6,6,0,0,0,0],
    },
  },
  {
    chapter: 'ladder-05',
    title: "Most of a week",
    teaches: "About as hard as a Wednesday.",
    difficulty: 2,
    board: {
      n: 9,
      stars: 2,
      regions: [5,5,4,4,4,7,7,7,7,5,5,2,4,7,7,7,3,3,5,2,2,4,4,7,7,3,3,5,2,2,2,2,7,6,3,3,5,5,2,8,8,6,6,6,3,8,2,2,8,6,6,6,6,1,8,8,8,8,8,6,6,1,1,0,0,0,0,0,1,1,1,1,0,0,0,0,1,1,1,1,1],
    },
  },
  {
    chapter: 'ladder-06',
    title: "Sunday sized",
    teaches: "This is what the weekend looks like.",
    difficulty: 3,
    board: {
      n: 10,
      stars: 2,
      regions: [9,9,9,9,9,4,4,4,7,7,9,9,9,9,9,4,4,4,4,7,9,6,9,9,9,9,4,2,4,7,6,6,9,9,8,2,4,2,2,7,6,6,1,8,8,2,2,2,2,8,6,1,1,1,8,8,8,8,8,8,6,1,1,1,3,0,0,0,8,8,6,6,1,5,3,3,0,0,0,8,6,6,5,5,3,3,0,0,0,0,6,5,5,3,3,3,3,0,0,0],
    },
  },
  {
    chapter: 'ladder-07',
    title: "The last one",
    teaches: "Finish this and the daily is yours.",
    difficulty: 3,
    board: {
      n: 10,
      stars: 2,
      regions: [9,9,9,9,5,3,3,3,3,3,9,9,5,5,5,3,3,3,3,0,8,8,5,5,5,3,6,3,0,0,8,8,8,8,8,3,6,3,3,0,8,8,8,8,8,6,6,0,0,0,8,7,2,8,2,6,6,1,0,0,7,7,2,2,2,2,6,1,1,1,7,7,7,7,2,4,6,6,1,1,7,4,4,4,4,4,4,6,1,1,4,4,4,4,4,4,6,6,1,1],
    },
  },
];
