/**
 * The difficulty ladder — generated by tools/build-ladder.ts, not written by hand.
 *
 * Rebuild with `pnpm ladder`. Do not edit: these boards are in players'
 * histories by level id, so changing one silently swaps the puzzle under
 * somebody's solved result.
 */

import type { Puzzle } from './engine';

/** Everything except the fields that identify a puzzle rather than describe it. */
export type Board = Omit<Puzzle, 'id' | 'game' | 'date' | 'number' | 'difficulty'>;

export interface Rung {
  chapter: string;
  title: string;
  teaches: string;
  difficulty: 1 | 2 | 3;
  /** kept behind its own key so it can be spread into a Puzzle without
      dragging the chapter's own fields in with it */
  board: Board;
}

export const LADDER: Rung[] = [
  {
    chapter: 'ladder-01',
    title: "On your own",
    teaches: "No new rules from here. Just boards.",
    difficulty: 1,
    board: {
      w: 5,
      h: 6,
      paths: [{"cells":[12,13,8,7,6],"dir":3},{"cells":[20,15,10,11,16],"dir":2},{"cells":[27,22,23,28],"dir":2},{"cells":[17,18,19,24],"dir":2}],
    },
  },
  {
    chapter: 'ladder-02',
    title: "A little more",
    teaches: "Same size, less given away.",
    difficulty: 1,
    board: {
      w: 5,
      h: 6,
      paths: [{"cells":[6,5,10,11,12],"dir":1},{"cells":[25,20,15,16],"dir":1},{"cells":[14,13,8,3,4],"dir":1},{"cells":[21,22,23],"dir":1}],
    },
  },
  {
    chapter: 'ladder-03',
    title: "Middling",
    teaches: "Bigger. Everything still follows.",
    difficulty: 2,
    board: {
      w: 6,
      h: 7,
      paths: [{"cells":[36,30,24],"dir":0},{"cells":[28,27,33,34,35,29],"dir":0},{"cells":[19,18,12,6,0,1],"dir":1},{"cells":[31,32,26,20,14],"dir":0},{"cells":[13,7,8],"dir":1},{"cells":[15,21,22],"dir":1},{"cells":[37,38,39],"dir":1},{"cells":[23,17,11],"dir":0}],
    },
  },
  {
    chapter: 'ladder-04',
    title: "Keep going",
    teaches: "You will need to look further ahead.",
    difficulty: 2,
    board: {
      w: 6,
      h: 7,
      paths: [{"cells":[15,9,3,2,8],"dir":2},{"cells":[1,0,6],"dir":2},{"cells":[29,28,27],"dir":3},{"cells":[24,18,19],"dir":1},{"cells":[20,26,25,31,32],"dir":1},{"cells":[36,37,38],"dir":1},{"cells":[21,22,23],"dir":1},{"cells":[39,33,34],"dir":1},{"cells":[11,17,16,10,4,5],"dir":1}],
    },
  },
  {
    chapter: 'ladder-05',
    title: "Most of a week",
    teaches: "About as hard as a Wednesday.",
    difficulty: 2,
    board: {
      w: 6,
      h: 7,
      paths: [{"cells":[25,24,30,36,37,31],"dir":0},{"cells":[41,35,34,40,39,33],"dir":0},{"cells":[1,2,8],"dir":2},{"cells":[6,7,13,14,15,9],"dir":0},{"cells":[22,16,10,4],"dir":0},{"cells":[27,28,29,23],"dir":0},{"cells":[21,20,26,32,38],"dir":2}],
    },
  },
  {
    chapter: 'ladder-06',
    title: "Sunday sized",
    teaches: "This is what the weekend looks like.",
    difficulty: 3,
    board: {
      w: 7,
      h: 8,
      paths: [{"cells":[51,52,45],"dir":0},{"cells":[25,26,19,12,5,6,13],"dir":2},{"cells":[10,17,24,31,38,37,30],"dir":0},{"cells":[48,55,54,53,46,47],"dir":1},{"cells":[49,50,43],"dir":0},{"cells":[9,16,15,22,29,28,21],"dir":0},{"cells":[18,11,4,3],"dir":3},{"cells":[33,32,39,40],"dir":1},{"cells":[2,1,8,7],"dir":3}],
    },
  },
  {
    chapter: 'ladder-07',
    title: "The last one",
    teaches: "Finish this and the daily is yours.",
    difficulty: 3,
    board: {
      w: 7,
      h: 8,
      paths: [{"cells":[13,6,5],"dir":3},{"cells":[26,19,12,11,4,3,10],"dir":2},{"cells":[48,55,54,53],"dir":3},{"cells":[0,1,8],"dir":2},{"cells":[22,21,28,29],"dir":1},{"cells":[45,38,31,24,17,16],"dir":3},{"cells":[32,39,40],"dir":1},{"cells":[30,37,36],"dir":3},{"cells":[50,51,44,43],"dir":3},{"cells":[35,42,49],"dir":2}],
    },
  },
];
