/**
 * The difficulty ladder — generated by tools/build-ladder.ts, not written by hand.
 *
 * Rebuild with `pnpm ladder`. Do not edit: these boards are in players'
 * histories by level id, so changing one silently swaps the puzzle under
 * somebody's solved result.
 */

import type { Puzzle } from './engine';

/** Everything except the fields that identify a puzzle rather than describe it. */
export type Board = Omit<Puzzle, 'id' | 'game' | 'date' | 'number' | 'difficulty'>;

export interface Rung {
  chapter: string;
  title: string;
  teaches: string;
  difficulty: 1 | 2 | 3;
  /** kept behind its own key so it can be spread into a Puzzle without
      dragging the chapter's own fields in with it */
  board: Board;
}

export const LADDER: Rung[] = [
  {
    chapter: 'ladder-01',
    title: "On your own",
    teaches: "No new rules from here. Just boards.",
    difficulty: 1,
    board: {
      w: 6,
      h: 6,
      clues: [2,-1,1,1,2,-1,2,-1,-1,1,-1,1,-1,-1,-1,-1,-1,-1,1,-1,-1,1,3,-1,-1,3,-1,-1,-1,-1,1,-1,-1,0,-1,0],
    },
  },
  {
    chapter: 'ladder-02',
    title: "A little more",
    teaches: "Same size, less given away.",
    difficulty: 1,
    board: {
      w: 6,
      h: 6,
      clues: [2,2,-1,-1,-1,-1,1,-1,-1,3,-1,-1,-1,-1,-1,3,-1,0,-1,-1,-1,2,-1,-1,1,0,0,-1,-1,1,-1,-1,-1,-1,1,-1],
    },
  },
  {
    chapter: 'ladder-03',
    title: "Middling",
    teaches: "Bigger. Everything still follows.",
    difficulty: 2,
    board: {
      w: 8,
      h: 8,
      clues: [-1,3,1,-1,-1,1,-1,2,-1,-1,-1,-1,-1,-1,-1,1,1,2,1,0,-1,0,-1,2,-1,-1,-1,-1,1,-1,-1,-1,-1,-1,1,3,-1,-1,0,-1,-1,-1,-1,-1,0,-1,-1,2,0,-1,-1,-1,-1,-1,3,2,-1,0,-1,-1,-1,-1,-1,-1],
    },
  },
  {
    chapter: 'ladder-04',
    title: "Keep going",
    teaches: "You will need to look further ahead.",
    difficulty: 2,
    board: {
      w: 8,
      h: 8,
      clues: [-1,0,-1,-1,-1,1,-1,-1,-1,-1,-1,2,1,3,-1,-1,-1,1,-1,-1,-1,-1,0,3,-1,-1,-1,0,-1,0,-1,-1,0,1,-1,-1,-1,-1,3,1,-1,-1,2,2,0,-1,-1,-1,0,-1,-1,-1,-1,-1,-1,1,-1,-1,-1,3,-1,1,1,-1],
    },
  },
  {
    chapter: 'ladder-05',
    title: "Most of a week",
    teaches: "About as hard as a Wednesday.",
    difficulty: 2,
    board: {
      w: 8,
      h: 8,
      clues: [-1,0,-1,2,-1,-1,1,2,1,-1,-1,0,-1,-1,-1,-1,-1,-1,-1,0,-1,-1,-1,1,2,0,1,2,-1,1,-1,3,-1,-1,2,-1,-1,-1,-1,-1,-1,2,-1,-1,-1,-1,-1,-1,-1,1,-1,0,-1,0,-1,-1,0,-1,-1,-1,-1,-1,-1,-1],
    },
  },
  {
    chapter: 'ladder-06',
    title: "Sunday sized",
    teaches: "This is what the weekend looks like.",
    difficulty: 3,
    board: {
      w: 10,
      h: 10,
      clues: [-1,-1,-1,2,-1,2,3,-1,3,-1,-1,-1,1,3,-1,-1,-1,-1,1,-1,-1,0,-1,-1,2,1,-1,-1,-1,1,-1,-1,-1,-1,3,-1,-1,-1,-1,2,-1,0,-1,-1,-1,1,-1,1,3,-1,0,-1,1,-1,1,0,-1,-1,1,2,-1,-1,-1,3,-1,-1,-1,-1,-1,-1,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,-1,-1,0,-1,0,-1,0,1,-1,0,-1,-1,1,-1,-1,1,-1,-1],
    },
  },
  {
    chapter: 'ladder-07',
    title: "The last one",
    teaches: "Finish this and the daily is yours.",
    difficulty: 3,
    board: {
      w: 10,
      h: 10,
      clues: [3,-1,-1,-1,2,-1,-1,1,1,-1,-1,-1,3,-1,-1,-1,0,-1,-1,-1,-1,-1,1,2,2,0,-1,-1,-1,2,-1,0,-1,2,-1,0,-1,-1,-1,3,-1,-1,-1,-1,-1,-1,0,-1,0,2,-1,-1,0,-1,1,-1,0,0,-1,-1,-1,-1,-1,1,1,-1,-1,-1,1,-1,0,-1,-1,-1,-1,-1,-1,1,-1,1,-1,-1,-1,-1,-1,0,-1,1,-1,-1,-1,-1,-1,-1,0,-1,-1,0,-1,-1],
    },
  },
];
